// Países membros da CPLP (Comunidade dos Países de Língua Portuguesa)
export const CPLP_COUNTRIES = [
  'Angola',
  'Brasil',
  'Cabo Verde',
  'Guiné-Bissau',
  'Guiné Equatorial',
  'Moçambique',
  'Portugal',
  'São Tomé e Príncipe',
  'Timor-Leste',
]

// Todos os outros países em ordem alfabética (português)
export const OTHER_COUNTRIES = [
  'Afeganistão',
  'África do Sul',
  'Albânia',
  'Alemanha',
  'Argélia',
  'Arménia',
  'Arábia Saudita',
  'Austrália',
  'Áustria',
  'Azerbaijão',
  'Bahrein',
  'Bangladesh',
  'Barbados',
  'Bélgica',
  'Bielorrússia',
  'Bolívia',
  'Bósnia e Herzegovina',
  'Botsuana',
  'Bulgária',
  'Burkina Faso',
  'Cambodja',
  'Camarões',
  'Canadá',
  'Cazaquistão',
  'Chile',
  'China',
  'Chipre',
  'Colômbia',
  'Congo',
  'Coreia do Sul',
  'Costa do Marfim',
  'Costa Rica',
  'Croácia',
  'Cuba',
  'Dinamarca',
  'Egipto',
  'El Salvador',
  'Emirados Árabes Unidos',
  'Equador',
  'Eritreia',
  'Eslováquia',
  'Eslovénia',
  'Espanha',
  'Estónia',
  'Estados Unidos',
  'Etiópia',
  'Filipinas',
  'Finlândia',
  'França',
  'Gâmbia',
  'Gana',
  'Geórgia',
  'Grécia',
  'Guatemala',
  'Guiana',
  'Haiti',
  'Honduras',
  'Hungria',
  'Índia',
  'Indonésia',
  'Irão',
  'Iraque',
  'Irlanda',
  'Israel',
  'Itália',
  'Jamaica',
  'Japão',
  'Jordânia',
  'Kosovo',
  'Kuwait',
  'Lesoto',
  'Letónia',
  'Líbano',
  'Líbia',
  'Lituânia',
  'Luxemburgo',
  'Macedónia do Norte',
  'Madagáscar',
  'Malawi',
  'Mali',
  'Malta',
  'Marrocos',
  'Maurícias',
  'México',
  'Mianmar',
  'Moldávia',
  'Montenegro',
  'Namíbia',
  'Nepal',
  'Nicarágua',
  'Nigéria',
  'Noruega',
  'Nova Zelândia',
  'Holanda',
  'Palestina',
  'Panamá',
  'Paquistão',
  'Paraguai',
  'Peru',
  'Polónia',
  'Qatar',
  'Reino Unido',
  'República Checa',
  'República Democrática do Congo',
  'República Dominicana',
  'Roménia',
  'Rússia',
  'Ruanda',
  'Senegal',
  'Serra Leoa',
  'Sérvia',
  'Somália',
  'Sri Lanka',
  'Sudão',
  'Suriname',
  'Suécia',
  'Suíça',
  'Síria',
  'Tailândia',
  'Tanzânia',
  'Trinidad e Tobago',
  'Tunísia',
  'Turquia',
  'Uganda',
  'Ucrânia',
  'Uruguai',
  'Uzbequistão',
  'Venezuela',
  'Vietname',
  'Eswatini',
  'Zimbabué',
  'Zâmbia',
]
